apiVersion: v1
kind: Secret
metadata:
  name: appsec # Name for your secret
type: Opaque # Opaque is commonly used for storing sensitive data like passwords
stringData:
  # Replace $T with the actual value you want to store
  cptoken: {{ .Values.cptoken }}